"""Register the Maestro daily digest as a Hermes cron job.

The digest is a self-contained ``no_agent`` cron job: it points at a tiny
launcher script under ``<HERMES_HOME>/scripts/`` (the only directory Hermes
cron will run scripts from) which runs the Maestro pipeline in LIVE mode. The
pipeline sends the digest to WhatsApp itself, so the cron ``deliver`` target is
``local`` (its stdout — a one-line run summary — is saved to the cron output).

Portability: the launcher resolves the Hermes repo root from
``MAESTRO_HERMES_ROOT`` / ``HERMES_SRC_ROOT`` (falling back to the path detected
at install time), so the same job definition moves cleanly to the Hetzner host.

This module never runs the gateway or restarts anything; it only writes a file
and appends a job to ``jobs.json`` via the public ``cron.jobs`` API.
"""

from __future__ import annotations

from pathlib import Path
from typing import Optional

LAUNCHER_NAME = "maestro_digest.py"
JOB_NAME = "maestro-daily-digest"

_LAUNCHER_TEMPLATE = '''#!/usr/bin/env python3
"""Auto-generated by `python -m maestro.cli install-cron`.

Maestro daily-digest cron launcher (LIVE mode → sends WhatsApp self-chat).
Configure via MAESTRO_* vars in <HERMES_HOME>/.env. Safe to regenerate.
"""
import os
import sys

_DEFAULT_ROOT = {repo_root!r}
_root = (
    os.environ.get("MAESTRO_HERMES_ROOT")
    or os.environ.get("HERMES_SRC_ROOT")
    or _DEFAULT_ROOT
)
if _root and _root not in sys.path:
    sys.path.insert(0, _root)

try:
    from maestro.cli import main
except Exception as exc:  # pragma: no cover - environment wiring
    sys.stderr.write(
        "maestro import failed; set MAESTRO_HERMES_ROOT to the Hermes repo "
        f"root. Error: {{exc}}\\n"
    )
    raise SystemExit(1)

raise SystemExit(main(["run"]))
'''


def detect_repo_root() -> str:
    """Repo root = the directory that contains the ``maestro`` package."""
    return str(Path(__file__).resolve().parents[1])


def render_launcher(repo_root: Optional[str] = None) -> str:
    return _LAUNCHER_TEMPLATE.format(repo_root=repo_root or detect_repo_root())


def cron_expression(hour: int, minute: int = 0) -> str:
    hour = max(0, min(23, int(hour)))
    minute = max(0, min(59, int(minute)))
    return f"{minute} {hour} * * *"


def write_launcher(scripts_dir: Path, repo_root: Optional[str] = None) -> Path:
    scripts_dir = Path(scripts_dir)
    scripts_dir.mkdir(parents=True, exist_ok=True)
    path = scripts_dir / LAUNCHER_NAME
    path.write_text(render_launcher(repo_root), encoding="utf-8")
    return path


def plan(config) -> dict:
    """Describe what install would do, without writing anything."""
    return {
        "job_name": JOB_NAME,
        "schedule": cron_expression(config.digest_hour),
        "timezone_note": (
            "Cron fires in the Hermes-configured timezone; set Hermes TZ to "
            f"{config.timezone} (or adjust MAESTRO_DIGEST_HOUR) so 07:00 means 07:00 BRT."
        ),
        "launcher": str((config.home / "scripts" / LAUNCHER_NAME)),
        "repo_root": detect_repo_root(),
        "deliver": "local (pipeline self-sends WhatsApp)",
        "no_agent": True,
    }


def install_cron(config, *, hour: Optional[int] = None, dry_run: bool = False) -> dict:
    """Write the launcher and create the cron job.

    With ``dry_run=True`` returns the :func:`plan` without side effects. A live
    install writes ``<HERMES_HOME>/scripts/maestro_digest.py`` and appends a job
    to ``jobs.json``; it does NOT start or restart the gateway.
    """
    if hour is None:
        hour = config.digest_hour
    if dry_run:
        p = plan(config)
        p["schedule"] = cron_expression(hour)
        p["dry_run"] = True
        return p

    scripts_dir = Path(config.home) / "scripts"
    launcher_path = write_launcher(scripts_dir, detect_repo_root())

    from cron.jobs import create_job

    job = create_job(
        prompt=None,
        schedule=cron_expression(hour),
        name=JOB_NAME,
        script=LAUNCHER_NAME,
        no_agent=True,
        deliver="local",
    )
    return {
        "dry_run": False,
        "launcher": str(launcher_path),
        "job_id": job.get("id"),
        "job_name": job.get("name"),
        "schedule": job.get("schedule_display"),
    }
